DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS user_profiles;
ALTER TABLE users DROP COLUMN IF EXISTS name;
ALTER TABLE users DROP COLUMN IF EXISTS avatar;
ALTER TABLE users DROP COLUMN IF EXISTS bio;
ALTER TABLE users DROP COLUMN IF EXISTS teach_skills;
ALTER TABLE users DROP COLUMN IF EXISTS learn_skills;
