// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: matchmaking/v1/matchmaking.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IHave         []string               `protobuf:"bytes,3,rep,name=i_have,json=iHave,proto3" json:"i_have,omitempty"`
	IWant         []string               `protobuf:"bytes,4,rep,name=i_want,json=iWant,proto3" json:"i_want,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetIHave() []string {
	if x != nil {
		return x.IHave
	}
	return nil
}

func (x *Profile) GetIWant() []string {
	if x != nil {
		return x.IWant
	}
	return nil
}

func (x *Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidatesRequest) Reset() {
	*x = GetCandidatesRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidatesRequest) ProtoMessage() {}

func (x *GetCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidatesRequest.ProtoReflect.Descriptor instead.
func (*GetCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{3}
}

func (x *GetCandidatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*Profile             `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidatesResponse) Reset() {
	*x = GetCandidatesResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidatesResponse) ProtoMessage() {}

func (x *GetCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidatesResponse.ProtoReflect.Descriptor instead.
func (*GetCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{4}
}

func (x *GetCandidatesResponse) GetCandidates() []*Profile {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SendExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExchangeRequest) Reset() {
	*x = SendExchangeRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExchangeRequest) ProtoMessage() {}

func (x *SendExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExchangeRequest.ProtoReflect.Descriptor instead.
func (*SendExchangeRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{5}
}

func (x *SendExchangeRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SendExchangeRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

type SendExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExchangeResponse) Reset() {
	*x = SendExchangeResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExchangeResponse) ProtoMessage() {}

func (x *SendExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExchangeResponse.ProtoReflect.Descriptor instead.
func (*SendExchangeResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{6}
}

func (x *SendExchangeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AcceptExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptExchangeRequest) Reset() {
	*x = AcceptExchangeRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptExchangeRequest) ProtoMessage() {}

func (x *AcceptExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptExchangeRequest.ProtoReflect.Descriptor instead.
func (*AcceptExchangeRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptExchangeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcceptExchangeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AcceptExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptExchangeResponse) Reset() {
	*x = AcceptExchangeResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptExchangeResponse) ProtoMessage() {}

func (x *AcceptExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptExchangeResponse.ProtoReflect.Descriptor instead.
func (*AcceptExchangeResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptExchangeResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type DeclineExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineExchangeRequest) Reset() {
	*x = DeclineExchangeRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineExchangeRequest) ProtoMessage() {}

func (x *DeclineExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineExchangeRequest.ProtoReflect.Descriptor instead.
func (*DeclineExchangeRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{9}
}

func (x *DeclineExchangeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeclineExchangeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type DeclineExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineExchangeResponse) Reset() {
	*x = DeclineExchangeResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineExchangeResponse) ProtoMessage() {}

func (x *DeclineExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineExchangeResponse.ProtoReflect.Descriptor instead.
func (*DeclineExchangeResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{10}
}

func (x *DeclineExchangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_matchmaking_v1_matchmaking_proto protoreflect.FileDescriptor

const file_matchmaking_v1_matchmaking_proto_rawDesc = "" +
	"\n" +
	" matchmaking/v1/matchmaking.proto\x12\x0ematchmaking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06i_have\x18\x03 \x03(\tR\x05iHave\x12\x15\n" +
	"\x06i_want\x18\x04 \x03(\tR\x05iWant\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\"I\n" +
	"\x14UpdateProfileRequest\x121\n" +
	"\aprofile\x18\x01 \x01(\v2\x17.matchmaking.v1.ProfileR\aprofile\"1\n" +
	"\x15UpdateProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x14GetCandidatesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"P\n" +
	"\x15GetCandidatesResponse\x127\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x17.matchmaking.v1.ProfileR\n" +
	"candidates\"U\n" +
	"\x13SendExchangeRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\"5\n" +
	"\x14SendExchangeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"O\n" +
	"\x15AcceptExchangeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"1\n" +
	"\x16AcceptExchangeResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"P\n" +
	"\x16DeclineExchangeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"3\n" +
	"\x17DeclineExchangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xed\x03\n" +
	"\x12MatchmakingService\x12\\\n" +
	"\rUpdateProfile\x12$.matchmaking.v1.UpdateProfileRequest\x1a%.matchmaking.v1.UpdateProfileResponse\x12\\\n" +
	"\rGetCandidates\x12$.matchmaking.v1.GetCandidatesRequest\x1a%.matchmaking.v1.GetCandidatesResponse\x12X\n" +
	"\vSendRequest\x12#.matchmaking.v1.SendExchangeRequest\x1a$.matchmaking.v1.SendExchangeResponse\x12^\n" +
	"\rAcceptRequest\x12%.matchmaking.v1.AcceptExchangeRequest\x1a&.matchmaking.v1.AcceptExchangeResponse\x12a\n" +
	"\x0eDeclineRequest\x12&.matchmaking.v1.DeclineExchangeRequest\x1a'.matchmaking.v1.DeclineExchangeResponseB8Z6github.com/QosmuratSamat0/pairexx/proto/matchmaking/v1b\x06proto3"

var (
	file_matchmaking_v1_matchmaking_proto_rawDescOnce sync.Once
	file_matchmaking_v1_matchmaking_proto_rawDescData []byte
)

func file_matchmaking_v1_matchmaking_proto_rawDescGZIP() []byte {
	file_matchmaking_v1_matchmaking_proto_rawDescOnce.Do(func() {
		file_matchmaking_v1_matchmaking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchmaking_v1_matchmaking_proto_rawDesc), len(file_matchmaking_v1_matchmaking_proto_rawDesc)))
	})
	return file_matchmaking_v1_matchmaking_proto_rawDescData
}

var file_matchmaking_v1_matchmaking_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_matchmaking_v1_matchmaking_proto_goTypes = []any{
	(*Profile)(nil),                 // 0: matchmaking.v1.Profile
	(*UpdateProfileRequest)(nil),    // 1: matchmaking.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),   // 2: matchmaking.v1.UpdateProfileResponse
	(*GetCandidatesRequest)(nil),    // 3: matchmaking.v1.GetCandidatesRequest
	(*GetCandidatesResponse)(nil),   // 4: matchmaking.v1.GetCandidatesResponse
	(*SendExchangeRequest)(nil),     // 5: matchmaking.v1.SendExchangeRequest
	(*SendExchangeResponse)(nil),    // 6: matchmaking.v1.SendExchangeResponse
	(*AcceptExchangeRequest)(nil),   // 7: matchmaking.v1.AcceptExchangeRequest
	(*AcceptExchangeResponse)(nil),  // 8: matchmaking.v1.AcceptExchangeResponse
	(*DeclineExchangeRequest)(nil),  // 9: matchmaking.v1.DeclineExchangeRequest
	(*DeclineExchangeResponse)(nil), // 10: matchmaking.v1.DeclineExchangeResponse
}
var file_matchmaking_v1_matchmaking_proto_depIdxs = []int32{
	0,  // 0: matchmaking.v1.UpdateProfileRequest.profile:type_name -> matchmaking.v1.Profile
	0,  // 1: matchmaking.v1.GetCandidatesResponse.candidates:type_name -> matchmaking.v1.Profile
	1,  // 2: matchmaking.v1.MatchmakingService.UpdateProfile:input_type -> matchmaking.v1.UpdateProfileRequest
	3,  // 3: matchmaking.v1.MatchmakingService.GetCandidates:input_type -> matchmaking.v1.GetCandidatesRequest
	5,  // 4: matchmaking.v1.MatchmakingService.SendRequest:input_type -> matchmaking.v1.SendExchangeRequest
	7,  // 5: matchmaking.v1.MatchmakingService.AcceptRequest:input_type -> matchmaking.v1.AcceptExchangeRequest
	9,  // 6: matchmaking.v1.MatchmakingService.DeclineRequest:input_type -> matchmaking.v1.DeclineExchangeRequest
	2,  // 7: matchmaking.v1.MatchmakingService.UpdateProfile:output_type -> matchmaking.v1.UpdateProfileResponse
	4,  // 8: matchmaking.v1.MatchmakingService.GetCandidates:output_type -> matchmaking.v1.GetCandidatesResponse
	6,  // 9: matchmaking.v1.MatchmakingService.SendRequest:output_type -> matchmaking.v1.SendExchangeResponse
	8,  // 10: matchmaking.v1.MatchmakingService.AcceptRequest:output_type -> matchmaking.v1.AcceptExchangeResponse
	10, // 11: matchmaking.v1.MatchmakingService.DeclineRequest:output_type -> matchmaking.v1.DeclineExchangeResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_matchmaking_v1_matchmaking_proto_init() }
func file_matchmaking_v1_matchmaking_proto_init() {
	if File_matchmaking_v1_matchmaking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchmaking_v1_matchmaking_proto_rawDesc), len(file_matchmaking_v1_matchmaking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matchmaking_v1_matchmaking_proto_goTypes,
		DependencyIndexes: file_matchmaking_v1_matchmaking_proto_depIdxs,
		MessageInfos:      file_matchmaking_v1_matchmaking_proto_msgTypes,
	}.Build()
	File_matchmaking_v1_matchmaking_proto = out.File
	file_matchmaking_v1_matchmaking_proto_goTypes = nil
	file_matchmaking_v1_matchmaking_proto_depIdxs = nil
}
