// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: matchmaking/v1/matchmaking.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchmakingService_UpdateProfile_FullMethodName  = "/matchmaking.v1.MatchmakingService/UpdateProfile"
	MatchmakingService_GetCandidates_FullMethodName  = "/matchmaking.v1.MatchmakingService/GetCandidates"
	MatchmakingService_SendRequest_FullMethodName    = "/matchmaking.v1.MatchmakingService/SendRequest"
	MatchmakingService_AcceptRequest_FullMethodName  = "/matchmaking.v1.MatchmakingService/AcceptRequest"
	MatchmakingService_DeclineRequest_FullMethodName = "/matchmaking.v1.MatchmakingService/DeclineRequest"
)

// MatchmakingServiceClient is the client API for MatchmakingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchmakingServiceClient interface {
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*GetCandidatesResponse, error)
	SendRequest(ctx context.Context, in *SendExchangeRequest, opts ...grpc.CallOption) (*SendExchangeResponse, error)
	AcceptRequest(ctx context.Context, in *AcceptExchangeRequest, opts ...grpc.CallOption) (*AcceptExchangeResponse, error)
	DeclineRequest(ctx context.Context, in *DeclineExchangeRequest, opts ...grpc.CallOption) (*DeclineExchangeResponse, error)
}

type matchmakingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchmakingServiceClient(cc grpc.ClientConnInterface) MatchmakingServiceClient {
	return &matchmakingServiceClient{cc}
}

func (c *matchmakingServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*GetCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCandidatesResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_GetCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) SendRequest(ctx context.Context, in *SendExchangeRequest, opts ...grpc.CallOption) (*SendExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendExchangeResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) AcceptRequest(ctx context.Context, in *AcceptExchangeRequest, opts ...grpc.CallOption) (*AcceptExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptExchangeResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_AcceptRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) DeclineRequest(ctx context.Context, in *DeclineExchangeRequest, opts ...grpc.CallOption) (*DeclineExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclineExchangeResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_DeclineRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchmakingServiceServer is the server API for MatchmakingService service.
// All implementations must embed UnimplementedMatchmakingServiceServer
// for forward compatibility.
type MatchmakingServiceServer interface {
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	GetCandidates(context.Context, *GetCandidatesRequest) (*GetCandidatesResponse, error)
	SendRequest(context.Context, *SendExchangeRequest) (*SendExchangeResponse, error)
	AcceptRequest(context.Context, *AcceptExchangeRequest) (*AcceptExchangeResponse, error)
	DeclineRequest(context.Context, *DeclineExchangeRequest) (*DeclineExchangeResponse, error)
	mustEmbedUnimplementedMatchmakingServiceServer()
}

// UnimplementedMatchmakingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchmakingServiceServer struct{}

func (UnimplementedMatchmakingServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedMatchmakingServiceServer) GetCandidates(context.Context, *GetCandidatesRequest) (*GetCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidates not implemented")
}
func (UnimplementedMatchmakingServiceServer) SendRequest(context.Context, *SendExchangeRequest) (*SendExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedMatchmakingServiceServer) AcceptRequest(context.Context, *AcceptExchangeRequest) (*AcceptExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptRequest not implemented")
}
func (UnimplementedMatchmakingServiceServer) DeclineRequest(context.Context, *DeclineExchangeRequest) (*DeclineExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeclineRequest not implemented")
}
func (UnimplementedMatchmakingServiceServer) mustEmbedUnimplementedMatchmakingServiceServer() {}
func (UnimplementedMatchmakingServiceServer) testEmbeddedByValue()                            {}

// UnsafeMatchmakingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchmakingServiceServer will
// result in compilation errors.
type UnsafeMatchmakingServiceServer interface {
	mustEmbedUnimplementedMatchmakingServiceServer()
}

func RegisterMatchmakingServiceServer(s grpc.ServiceRegistrar, srv MatchmakingServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchmakingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchmakingService_ServiceDesc, srv)
}

func _MatchmakingService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_GetCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).GetCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_GetCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).GetCandidates(ctx, req.(*GetCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).SendRequest(ctx, req.(*SendExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_AcceptRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).AcceptRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_AcceptRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).AcceptRequest(ctx, req.(*AcceptExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_DeclineRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclineExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).DeclineRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_DeclineRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).DeclineRequest(ctx, req.(*DeclineExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchmakingService_ServiceDesc is the grpc.ServiceDesc for MatchmakingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchmakingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchmaking.v1.MatchmakingService",
	HandlerType: (*MatchmakingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateProfile",
			Handler:    _MatchmakingService_UpdateProfile_Handler,
		},
		{
			MethodName: "GetCandidates",
			Handler:    _MatchmakingService_GetCandidates_Handler,
		},
		{
			MethodName: "SendRequest",
			Handler:    _MatchmakingService_SendRequest_Handler,
		},
		{
			MethodName: "AcceptRequest",
			Handler:    _MatchmakingService_AcceptRequest_Handler,
		},
		{
			MethodName: "DeclineRequest",
			Handler:    _MatchmakingService_DeclineRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matchmaking/v1/matchmaking.proto",
}
